# kubeadm-config.yaml
kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta3
networking:
  serviceSubnet: 10.97.0.0/16
  podSubnet: 10.245.0.0/16
  dnsDomain: cluster.local
kubernetesVersion: v1.29.0
controlPlaneEndpoint: k8s-mstr-u-priv.clemenslabs.com
---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: systemd
